function aesthetic() {
  document.getElementById('shot1').src = 'shirtxl1.jpeg';
  document.getElementById('shot2').src = 'shirtxl2.jpg';
  document.getElementById('shot3').src = 'shirtxl3.jpeg';
  document.getElementById('shot4').src = 'shirtxl4.jpeg';
  document.getElementById('shot5').src = 'shirtxl5.jpg';
  document.getElementById('shot6').src = 'shirtxl6.jpeg';
  document.getElementById('Name1').innerHTML='Cotton Oversize Black Shirt';
  document.getElementById('Name2').innerHTML='Cotton Oversize One Peace';
  document.getElementById('Name3').innerHTML='Cotton Oversize One Peace';
  document.getElementById('Name4').innerHTML='Cotton Oversize Naruto';
  document.getElementById('Name5').innerHTML='Cotton Oversize One Peace';
  document.getElementById('Name6').innerHTML='Cotton Oversize Kamekazee';
  document.getElementById('value1').innerHTML='₱ 450.00';
  document.getElementById('place1').innerHTML = '<a class="click1" href="Buying.html"><button class="buy1">Buy Now!</button></a>';
  document.getElementById('value2').innerHTML='₱ 450.00';
  document.getElementById('place2').innerHTML = '<a class="click2" href="Buying - Copy.html"><button class="buy2">Buy Now!</button></a>';
  document.getElementById('value3').innerHTML='₱ 450.00';
  document.getElementById('place3').innerHTML = '<a class="click3" href="Buying - Copy (2).html"><button class="buy3">Buy Now!</button></a>';
  document.getElementById('value4').innerHTML='₱ 450.00';
  document.getElementById('place4').innerHTML = '<a class="click4" href="Buying - Copy (3).html"><button class="buy4">Buy Now!</button></a>';
  document.getElementById('value5').innerHTML='₱ 450.00';
  document.getElementById('place5').innerHTML = '<a class="click5" href="Buying - Copy (4).html"><button class="buy5">Buy Now!</button></a>';
  document.getElementById('value6').innerHTML='₱ 450.00';
  document.getElementById('place6').innerHTML = '<a class="click6" href="Buying - Copy (5).html"><button class="buy6">Buy Now!</button></a>';
}
function couple() {
  document.getElementById('shot1').src='couple1.jpeg';
  document.getElementById('shot2').src='couple2.jpg';
  document.getElementById('shot3').src='couple3.jpg';
  document.getElementById('shot4').src='coulple4.jpg';
  document.getElementById('shot5').src='couple5.jpg';
  document.getElementById('shot6').src='couple6.jpg';
  document.getElementById('Name1').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('Name2').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('Name3').innerHTML='Cotton Oversize Couple  Shirt';
  document.getElementById('Name4').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('Name5').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('Name6').innerHTML='Cotton Oversize Couple Shirt';
  document.getElementById('value1').innerHTML = '₱ 280.00';
  document.getElementById('place1').innerHTML = '<a class="click1" href="Buying - Copy (6).html"><button class="buy1">Buy Now!</button></a>';
  document.getElementById('value2').innerHTML = '₱ 280.00';
  document.getElementById('place2').innerHTML = '<a class="click2" href="Buying - Copy (7).html"><button class="buy2">Buy Now!</button></a>';
  document.getElementById('value3').innerHTML = '₱ 280.00';
  document.getElementById('place3').innerHTML = '<a class="click3" href="Buying - Copy (8).html"><button class="buy3">Buy Now!</button></a>';
  document.getElementById('value4').innerHTML = '₱ 280.00';
  document.getElementById('place4').innerHTML = '<a class="click4" href="Buying - Copy (9).html"><button class="buy4">Buy Now!</button></a>';
  document.getElementById('value5').innerHTML = '₱ 280.00';
  document.getElementById('place5').innerHTML = '<a class="click5" href="Buying - Copy (10).html"><button class="buy5">Buy Now!</button></a>';
  document.getElementById('value6').innerHTML = '₱ 280.00';
  document.getElementById('place6').innerHTML = '<a class="click6" href="Buying - Copy (11).html"><button class="buy6">Buy Now!</button></a>';
}
function Doodle() {
  document.getElementById('shot1').src = 'doodle1.jpeg';
  document.getElementById('shot2').src = 'doodle2.jpeg';
  document.getElementById('shot3').src = 'doodle3.jpeg';
  document.getElementById('shot4').src = 'doodle4.jpeg';
  document.getElementById('shot5').src = 'doodle5.jpg';
  document.getElementById('shot6').src = 'doodle6.jpg';
  document.getElementById('Name1').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name2').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name3').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name4').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name5').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('Name6').innerHTML='Cotton Oversize Doodle Shirt';
  document.getElementById('value1').innerHTML = '₱ 350.00';
  document.getElementById('place1').innerHTML = '<a class="click1" href="Buying - Copy (12).html"><button class="buy1">Buy Now!</button></a>';
  document.getElementById('value2').innerHTML = '₱ 350.00';
  document.getElementById('place2').innerHTML = '<a class="click2" href="Buying - Copy (13).html"><button class="buy2">Buy Now!</button></a>';
  document.getElementById('value3').innerHTML = '₱ 350.00';
  document.getElementById('place3').innerHTML = '<a class="click3" href="Buying - Copy (14).html"><button class="buy3">Buy Now!</button></a>';
  document.getElementById('value4').innerHTML = '₱ 350.00';
  document.getElementById('place4').innerHTML = '<a class="click4" href="Buying - Copy (15).html"><button class="buy4">Buy Now!</button></a>';
  document.getElementById('value5').innerHTML = '₱ 350.00';
  document.getElementById('place5').innerHTML = '<a class="click5" href="Buying - Copy (16).html"><button class="buy5">Buy Now!</button></a>';
  document.getElementById('value6').innerHTML = '₱ 350.00';
  document.getElementById('place6').innerHTML = '<a class="click6" href="Buying - Copy (17).html"><button class="buy6">Buy Now!</button></a>';
}
function Plain() {
  document.getElementById('shot1').src = 'plain1.jpeg';
  document.getElementById('shot2').src = 'plain2.jpeg';
  document.getElementById('shot3').src = 'plain3.jpeg';
  document.getElementById('shot4').src = 'plain4.jpeg';
  document.getElementById('shot5').src = 'plain5.jpeg';
  document.getElementById('shot6').src = 'plain6.jpeg';
  document.getElementById('Name1').innerHTML='Cotton Oversize Pink Shirt';
  document.getElementById('Name2').innerHTML='Cotton Oversize Black Shirt';
  document.getElementById('Name3').innerHTML='Cotton Oversize Gray Shirt';
  document.getElementById('Name4').innerHTML='Cotton Oversize Mint Shirt';
  document.getElementById('Name5').innerHTML='Cotton Oversize Green Shirt';
  document.getElementById('Name6').innerHTML='Cotton Oversize LightBrown Shirt';
  document.getElementById('value1').innerHTML = '₱ 180.00';
  document.getElementById('place1').innerHTML = '<a class="click1" href="Buying - Copy (18).html"><button class="buy1">Buy Now!</button></a>';
  document.getElementById('value2').innerHTML = '₱ 180.00';
  document.getElementById('place2').innerHTML = '<a class="click2" href="Buying - Copy (19).html"><button class="buy2">Buy Now!</button></a>';
  document.getElementById('value3').innerHTML = '₱ 180.00';
  document.getElementById('place3').innerHTML = '<a class="click3" href="Buying - Copy (20).html"><button class="buy3">Buy Now!</button></a>';
  document.getElementById('value4').innerHTML = '₱ 180.00';
  document.getElementById('place4').innerHTML = '<a class="click4" href="Buying - Copy (21).html"><button class="buy4">Buy Now!</button></a>';
  document.getElementById('value5').innerHTML = '₱ 180.00';
  document.getElementById('place5').innerHTML = '<a class="click5" href="Buying - Copy (22).html"><button class="buy5">Buy Now!</button></a>';
  document.getElementById('value6').innerHTML = '₱ 180.00';
  document.getElementById('place6').innerHTML = '<a class="click6" href="Buying - Copy (23).html"><button class="buy6">Buy Now!</button></a>';
}